services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: discworld
      POSTGRES_PASSWORD: discworld
      POSTGRES_DB: discworld
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
